# Workflow to run test and build the project

name: Build and Test

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-v2:
    runs-on: ubuntu-latest
    environment: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress Run
        uses: cypress-io/github-action@v5
        with:
          start: npm run dev-lite
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DYNAMODB_TABLE_NAME: ${{ vars.DYNAMODB_TABLE_NAME }}

