# Workflow to run test and build the project

name: Build and Test

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-v2:
    runs-on: ubuntu-latest
    environment: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress Run
        uses: cypress-io/github-action@v5
        with:
          start: npm run dev-lite
  build:
    runs-on: ubuntu-latest
    environment: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm run e2etest
