# Workflow to run test and build the project

name: Build and Test

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Debug Print node NODE_OPTIONS
        run: echo $NODE_OPTIONS
      - name: Run Tests
        run: unset NODE_OPTIONS && npm run e2etest